name: Docker

on:
  workflow_dispatch:

env:
  REGISTRY: crpi-juuq9gkz24fdpj2r.cn-beijing.personal.cr.aliyuncs.com

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: docker/setup-buildx-action@master
    - run: |
        image=$(head -n 1 docker.txt)
        new_image=$REGISTRY/wangluting/$(basename $image)

        docker login -u luting王 -p ${{ secrets.DOCKER_PASSWORD }} $REGISTRY

        docker pull $image
        docker tag $image $new_image
        docker push $new_image

